# tasks/download_stations_data/config.yaml

# GBFS version
version: "1.1"  # Only 1.1 currently supported

# What to download
download_metadata: true   # Station information + regions (download occasionally)
download_status: false     # Current station status (download regularly)

# Storage location
output_storage: "local"  # "local" or "drive"